version: "3.8"
services:
  backend:
    build: ./core
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True

  bot:
    build: ./core
    command: python manage.py run_bot
    volumes:
      - ./core:/app

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  #
    environment:
      - NODE_ENV=development
