version: '3.8'

services:
  postgres:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: botdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  core:
    build: ./core
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - DATABASE_URL=postgres://root:123456@postgres:5432/botdb

  bot:
    depends_on:
      - postgres
    build: ./core
    container_name: bot
    command: python manage.py run_bot
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      - DATABASE_URL=postgres://root:123456@postgres:5432/botdb

volumes:
  postgres-data:
