version: "3.8"

services:

  django_app:
    image: django_app
    build:
      context: ./core
    container_name: "django_cont"
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py createsuperuser && python manage.py runserver 0.0.0.0:8000 && python manage.py makemigrations && python manage.py migrate && python manage.py run_bot"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=Qias83.1383
      - MYSQL_DATABASE=marzbanbot_db