version: '3.8'

services:
  core:
    build: ./core
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      # SQLite does not require DATABASE_URL

  bot:
    build: ./core
    container_name: bot
    command: python manage.py run_bot
    volumes:
      - ./core:/app
    environment:
      - SECRET_KEY=test
      - DEBUG=True
      # SQLite does not require DATABASE_URL
