# Generated by Django 3.2 on 2023-11-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_proxycategory_configuration_panel_url_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='panel_password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='panel_username',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=4),
        ),
    ]
