# Generated by Django 3.2 on 2023-11-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20231102_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='text',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='telegram_id',
            field=models.CharField(default=None, max_length=2043),
        ),
    ]
