# Generated by Django 3.2 on 2024-01-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20231115_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.DeleteModel(
            name='ProxyCategory',
        ),
    ]
