# Generated by Django 4.0 on 2024-02-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20240128_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotUser',
        ),
    ]
