# Generated by Django 4.0 on 2024-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_user_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
